// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FCG.UsersAPI.Tests.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeUsuariosFeature : object, global::Xunit.IClassFixture<GerenciamentoDeUsuariosFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "BDD/Features", "Gerenciamento de Usuários", "  Como sistema de gerenciamento de usuários\r\n  Quero registrar e gerenciar usuári" +
                "os\r\n  Para que possam acessar a plataforma FCG Games", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UserService.feature"
#line hidden
        
        public GerenciamentoDeUsuariosFeature(GerenciamentoDeUsuariosFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("BDD/Features/UserService.feature", "Feature: Gerenciamento de Usuários\n  Como sistema de gerenciamento de usuários\n  " +
                    "Quero registrar e gerenciar usuários\n  Para que possam acessar a plataforma FCG " +
                    "Games\n\n  # ---- RegisterAsync ----\n\n  Scenario: Registrar usuário com dados invá" +
                    "lidos retorna falha\n    When o sistema tenta registrar um usuário com dados invá" +
                    "lidos\n    Then o resultado de registro deve ser falha com mensagem \"Invalid requ" +
                    "est data\"\n\n  Scenario: Registrar usuário com e-mail já cadastrado retorna falha\n" +
                    "    Given já existe um usuário cadastrado com o e-mail \"existente@fcg.com\"\n    W" +
                    "hen o sistema tenta registrar um usuário com o mesmo e-mail \"existente@fcg.com\"\n" +
                    "    Then o resultado de registro deve ser falha com mensagem \"Usuário já cadastr" +
                    "ado\"\n\n  Scenario: Registrar usuário com dados válidos retorna sucesso\n    When o" +
                    " sistema registra um usuário com nome \"João Silva\" e-mail \"joao@fcg.com\" e senha" +
                    " \"Senha@123\"\n    Then o resultado de registro deve ser sucesso\n    And o usuário" +
                    " retornado deve ter nome \"João Silva\"\n    And o usuário retornado deve ter e-mai" +
                    "l \"joao@fcg.com\"\n\n  Scenario: Registrar usuário com dados válidos publica evento" +
                    " de criação\n    When o sistema registra um usuário com nome \"Maria Santos\" e-mai" +
                    "l \"maria@fcg.com\" e senha \"Senha@123\"\n    Then o evento de criação de usuário de" +
                    "ve ter sido publicado\n\n  Scenario: Registrar usuário com dados válidos chama rep" +
                    "ositório para adicionar\n    When o sistema registra um usuário com nome \"Carlos " +
                    "Souza\" e-mail \"carlos@fcg.com\" e senha \"Senha@123\"\n    Then o repositório deve t" +
                    "er sido chamado para adicionar o usuário\n\n  # ---- GetAll ----\n\n  Scenario: List" +
                    "ar todos os usuários retorna a lista completa\n    Given 3 usuários cadastrados n" +
                    "o sistema\n    When todos os usuários são listados\n    Then devem ser retornados " +
                    "3 usuários\n\n  Scenario: Listar usuários com repositório vazio retorna lista vazi" +
                    "a\n    Given nenhum usuário cadastrado no sistema\n    When todos os usuários são " +
                    "listados\n    Then devem ser retornados 0 usuários\n\n  # ---- GetById ----\n\n  Scen" +
                    "ario: Buscar usuário por id existente retorna o usuário\n    Given um usuário cad" +
                    "astrado no sistema\n    When o sistema busca o usuário pelo id cadastrado\n    The" +
                    "n o usuário deve ser retornado com sucesso\n\n  Scenario: Buscar usuário por id in" +
                    "existente retorna nulo\n    When o sistema busca um usuário por id inexistente\n  " +
                    "  Then o resultado deve ser nulo\n\n  # ---- Update ----\n\n  Scenario: Atualizar us" +
                    "uário inexistente retorna nulo\n    When o sistema tenta atualizar um usuário com" +
                    " id inexistente\n    Then o resultado deve ser nulo\n\n  Scenario: Atualizar usuári" +
                    "o existente com novo nome\n    Given um usuário cadastrado no sistema\n    When o " +
                    "sistema atualiza o usuário com o nome \"Novo Nome Atualizado\"\n    Then o usuário " +
                    "deve ter nome \"Novo Nome Atualizado\"\n    And o repositório deve ter sido chamado" +
                    " para atualizar o usuário\n\n  Scenario: Desativar usuário existente\n    Given um " +
                    "usuário cadastrado no sistema\n    When o sistema desativa o usuário\n    Then o u" +
                    "suário deve estar inativo\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("BDD/Features/UserService.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Gerenciamento de Usuários", "  Como sistema de gerenciamento de usuários\r\n  Quero registrar e gerenciar usuári" +
                        "os\r\n  Para que possam acessar a plataforma FCG Games", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com dados inválidos retorna falha", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema tenta registrar um usuário com dados inválidos", null, null, "ed53aeb000857c548a0ecd684ccd363b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado de registro deve ser falha com mensagem \"Invalid request data\"", null, null, "4bd0032d42ae6c5c854e53acd74741a5")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "ebc2f0ec30315156ad3ac9ea6fa39746")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com e-mail já cadastrado retorna falha", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "já existe um usuário cadastrado com o e-mail \"existente@fcg.com\"", null, null, "09933386f7f59151b3cba5af596476d1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema tenta registrar um usuário com o mesmo e-mail \"existente@fcg.com\"", null, null, "415f17c50d90315493c142edf0d61119"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado de registro deve ser falha com mensagem \"Usuário já cadastrado\"", null, null, "49c19183ad11da509f40533d431d80d8")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "463574fc8e1b7e5e833b12dc21fef942")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com dados válidos retorna sucesso", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema registra um usuário com nome \"João Silva\" e-mail \"joao@fcg.com\" e senha" +
                                                            " \"Senha@123\"", null, null, "2bcc1bce7c271256bb916814f19b0d83"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado de registro deve ser sucesso", null, null, "9990a2afcc1cd55197a5416edbf101fb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o usuário retornado deve ter nome \"João Silva\"", null, null, "b088697848672451a4fca1e824bf5c92"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o usuário retornado deve ter e-mail \"joao@fcg.com\"", null, null, "4188b62205589f51b8368c50ed44cdd0")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "42be382d893e3255ad18b6ab5da32a34")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com dados válidos publica evento de criação", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema registra um usuário com nome \"Maria Santos\" e-mail \"maria@fcg.com\" e se" +
                                                            "nha \"Senha@123\"", null, null, "09abdf38f35d7954b5899ff9ed3b83b2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o evento de criação de usuário deve ter sido publicado", null, null, "e4917d48781c0b56a318d482af66d267")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "df17859348ceb1569b0e55f3add11ceb")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com dados válidos chama repositório para adicionar", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema registra um usuário com nome \"Carlos Souza\" e-mail \"carlos@fcg.com\" e s" +
                                                            "enha \"Senha@123\"", null, null, "9310d67cd7212b56955aa42bf65ca44e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o repositório deve ter sido chamado para adicionar o usuário", null, null, "636c9e8a85f53f559082128662ce672e")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "246f0f68dda6f15680fac691a15110c8")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Listar todos os usuários retorna a lista completa", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "3 usuários cadastrados no sistema", null, null, "c58d0f6efdda705f91501e931175dd2c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "todos os usuários são listados", null, null, "0afa44f30f67d159b2cb564d03332657"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devem ser retornados 3 usuários", null, null, "78b61992efc63053837a76458550feed")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "dd199a3dd1173358a8eb1e3c5a5f7207")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Listar usuários com repositório vazio retorna lista vazia", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "nenhum usuário cadastrado no sistema", null, null, "9699a881fce84659b8094476df350009"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "todos os usuários são listados", null, null, "3397b9ab2b98965f906d0c8c99570619"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devem ser retornados 0 usuários", null, null, "a003a510c75353569d81e5bfee8a5ad7")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "24b1a57f1eae135a8a6d86f4a385771b")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Buscar usuário por id existente retorna o usuário", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um usuário cadastrado no sistema", null, null, "6bf930181c1d035eb717f3b4a7581429"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema busca o usuário pelo id cadastrado", null, null, "3760739d04f50d539b6b9acde59f20c3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o usuário deve ser retornado com sucesso", null, null, "aac96a02e64fe65f9ea62c2bc6e378fb")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "039ce3cb38e5d35fa790062a897a6b06")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Buscar usuário por id inexistente retorna nulo", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema busca um usuário por id inexistente", null, null, "cc28b39101bbbb5eb5c267c7c9093b99"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado deve ser nulo", null, null, "924f1cd4b1edbc568e7daafeb822251a")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "c6052d7aab5fa05dbd77b56a860e7ca1")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Atualizar usuário inexistente retorna nulo", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema tenta atualizar um usuário com id inexistente", null, null, "0e61620bf4e5df57bcd8c63bb965b0e3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(58, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado deve ser nulo", null, null, "7db4fc35b7152457b684ede066df40cd")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3342f9db3139575fb03e8b2ace5b4c4c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Atualizar usuário existente com novo nome", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um usuário cadastrado no sistema", null, null, "cd67e11197319653a7c9e09acd33d4d7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema atualiza o usuário com o nome \"Novo Nome Atualizado\"", null, null, "15029d98cbf46951b5aaf81190ed4c8b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(63, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o usuário deve ter nome \"Novo Nome Atualizado\"", null, null, "3d7acc7cfc6d115198f7f3a54142a8e6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(64, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o repositório deve ter sido chamado para atualizar o usuário", null, null, "18888704a571b452bda0dfd0ca4c7415")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e1dd320d415b9c56a6c63d8248123c65")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(66, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Desativar usuário existente", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(67, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um usuário cadastrado no sistema", null, null, "6736746d1a700f5da245ce23e8167c7f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(68, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema desativa o usuário", null, null, "3128b82d8fe6c7528904cc4cb7d371b1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(69, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o usuário deve estar inativo", null, null, "1dc85835e786645aa12eae7d17beb4c3")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "57f1c5ada060f85fb292736b18e1a3c3"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[] {
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), "  # ---- RegisterAsync ----"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(1)), "  # ---- GetAll ----"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(43, new System.Nullable<long>(1)), "  # ---- GetById ----"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(1)), "  # ---- Update ----")}));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("696cab86b26dfe52bbd92b3f26543dc9", "BDD/Features/UserService.feature", "Registrar usuário com dados inválidos retorna falha", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ed53aeb000857c548a0ecd684ccd363b"}), "09e7251013110050aab2e63fbdb87f9b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema tenta registrar um usuário com dados inválidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4bd0032d42ae6c5c854e53acd74741a5"}), "5cb9cd14426b5352960d27f846cf9582", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado de registro deve ser falha com mensagem \"Invalid request data\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "ebc2f0ec30315156ad3ac9ea6fa39746"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3247a7fe21696c518d20b4a2dba36234", "BDD/Features/UserService.feature", "Registrar usuário com e-mail já cadastrado retorna falha", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "09933386f7f59151b3cba5af596476d1"}), "19c0f12043d88e59bcbb09b54115266c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "já existe um usuário cadastrado com o e-mail \"existente@fcg.com\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "415f17c50d90315493c142edf0d61119"}), "345b742f81b96f5587a8a36980415638", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema tenta registrar um usuário com o mesmo e-mail \"existente@fcg.com\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "49c19183ad11da509f40533d431d80d8"}), "051326bb189f2c51a96fef7397ab516e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado de registro deve ser falha com mensagem \"Usuário já cadastrado\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "463574fc8e1b7e5e833b12dc21fef942"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("0e35a3a48511e15bbb8e328da2c69313", "BDD/Features/UserService.feature", "Registrar usuário com dados válidos retorna sucesso", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2bcc1bce7c271256bb916814f19b0d83"}), "ea3bdea7448a7c528891ce84fd157777", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema registra um usuário com nome \"João Silva\" e-mail \"joao@fcg.com\" e senha" +
                                                " \"Senha@123\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9990a2afcc1cd55197a5416edbf101fb"}), "13e4886491a9a550bbaa5d164a6fab02", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado de registro deve ser sucesso"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b088697848672451a4fca1e824bf5c92"}), "e11fe8e30ecff154958edab2948373e2", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário retornado deve ter nome \"João Silva\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4188b62205589f51b8368c50ed44cdd0"}), "228df168f97f2f5bbedaf65d39518289", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário retornado deve ter e-mail \"joao@fcg.com\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "42be382d893e3255ad18b6ab5da32a34"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d6b03bdd22088559923d8ca93e74f41c", "BDD/Features/UserService.feature", "Registrar usuário com dados válidos publica evento de criação", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "09abdf38f35d7954b5899ff9ed3b83b2"}), "4d2c4dd92f13b75c9f998e03c71e6e98", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema registra um usuário com nome \"Maria Santos\" e-mail \"maria@fcg.com\" e se" +
                                                "nha \"Senha@123\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e4917d48781c0b56a318d482af66d267"}), "88233d9e41df235086cccbbfcab475e5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o evento de criação de usuário deve ter sido publicado")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "df17859348ceb1569b0e55f3add11ceb"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("41591e0086b96b528661ef0887fbe5b4", "BDD/Features/UserService.feature", "Registrar usuário com dados válidos chama repositório para adicionar", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9310d67cd7212b56955aa42bf65ca44e"}), "16369e8ad2079156853210fd1ddd85f2", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema registra um usuário com nome \"Carlos Souza\" e-mail \"carlos@fcg.com\" e s" +
                                                "enha \"Senha@123\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "636c9e8a85f53f559082128662ce672e"}), "cd820f4a0de89556bacd5b0de13377d1", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o repositório deve ter sido chamado para adicionar o usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "246f0f68dda6f15680fac691a15110c8"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("8f8c04168ef3bb5f88e27d154ed2f9fb", "BDD/Features/UserService.feature", "Listar todos os usuários retorna a lista completa", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c58d0f6efdda705f91501e931175dd2c"}), "c80efb56cfc5ac5f8bd40190aa1b161e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "3 usuários cadastrados no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0afa44f30f67d159b2cb564d03332657"}), "e4d4a5b9fca1d25b82e4c64af743b4d3", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "todos os usuários são listados"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "78b61992efc63053837a76458550feed"}), "69e642ce83a0375fa4c470c337c6793d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devem ser retornados 3 usuários")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "dd199a3dd1173358a8eb1e3c5a5f7207"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("9698f4838d791950acc28c08897765db", "BDD/Features/UserService.feature", "Listar usuários com repositório vazio retorna lista vazia", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9699a881fce84659b8094476df350009"}), "b383a4a690a4fd59a262702fd7188c08", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "nenhum usuário cadastrado no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3397b9ab2b98965f906d0c8c99570619"}), "a15020bf26b410528e9b7c0b2716974f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "todos os usuários são listados"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a003a510c75353569d81e5bfee8a5ad7"}), "44afe1c59e90b95f980b79856032edf7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devem ser retornados 0 usuários")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "24b1a57f1eae135a8a6d86f4a385771b"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("7a3e00563244b65e83d2abdec86e31f9", "BDD/Features/UserService.feature", "Buscar usuário por id existente retorna o usuário", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6bf930181c1d035eb717f3b4a7581429"}), "252ba898af64ba5988e06380ddd74917", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um usuário cadastrado no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3760739d04f50d539b6b9acde59f20c3"}), "44c29d3a9a03885c9c2171effaa4173f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema busca o usuário pelo id cadastrado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "aac96a02e64fe65f9ea62c2bc6e378fb"}), "04b95867a648dc57b568f051bfe423be", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário deve ser retornado com sucesso")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "039ce3cb38e5d35fa790062a897a6b06"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3b133eaf1db1d95eaf99626bd79b3faa", "BDD/Features/UserService.feature", "Buscar usuário por id inexistente retorna nulo", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cc28b39101bbbb5eb5c267c7c9093b99"}), "d1a70703b56dba5fa06930b8537923e3", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema busca um usuário por id inexistente"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "924f1cd4b1edbc568e7daafeb822251a"}), "b9f8d50337b2b85c9600f42956257db1", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado deve ser nulo")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "c6052d7aab5fa05dbd77b56a860e7ca1"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("71cc27dbfd664657980100a823806eba", "BDD/Features/UserService.feature", "Atualizar usuário inexistente retorna nulo", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0e61620bf4e5df57bcd8c63bb965b0e3"}), "6d2b4c41f869105da2b9faf850f6dcae", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema tenta atualizar um usuário com id inexistente"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7db4fc35b7152457b684ede066df40cd"}), "74fd228b7ad72d5ca2ef7374c9152794", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado deve ser nulo")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "3342f9db3139575fb03e8b2ace5b4c4c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d9b51a9ca4e9535bbe2142405ba9ef42", "BDD/Features/UserService.feature", "Atualizar usuário existente com novo nome", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cd67e11197319653a7c9e09acd33d4d7"}), "d2ba1b2d3245ac5393f658b9acbc17d9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um usuário cadastrado no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "15029d98cbf46951b5aaf81190ed4c8b"}), "e08342acee2f3d5f8048ae685683aa4d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema atualiza o usuário com o nome \"Novo Nome Atualizado\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3d7acc7cfc6d115198f7f3a54142a8e6"}), "142a6a2e5da98254a49a16e81c425fac", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário deve ter nome \"Novo Nome Atualizado\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "18888704a571b452bda0dfd0ca4c7415"}), "97be623b60e11e589b3e53f612ec3d46", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o repositório deve ter sido chamado para atualizar o usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "e1dd320d415b9c56a6c63d8248123c65"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3a2423d6052be050be685243703e695e", "BDD/Features/UserService.feature", "Desativar usuário existente", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6736746d1a700f5da245ce23e8167c7f"}), "14267cf36e5a535b91591d9d0b01d5fc", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um usuário cadastrado no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3128b82d8fe6c7528904cc4cb7d371b1"}), "f2ad0d79ec6ee25bbdf775715c29baef", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema desativa o usuário"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1dc85835e786645aa12eae7d17beb4c3"}), "f12c9d9619d87158821af57dcc2858f1", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário deve estar inativo")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "57f1c5ada060f85fb292736b18e1a3c3"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(GerenciamentoDeUsuariosFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(GerenciamentoDeUsuariosFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(GerenciamentoDeUsuariosFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com dados inválidos retorna falha")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com dados inválidos retorna falha")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComDadosInvalidosRetornaFalha()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com dados inválidos retorna falha", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.WhenAsync("o sistema tenta registrar um usuário com dados inválidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync("o resultado de registro deve ser falha com mensagem \"Invalid request data\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com e-mail já cadastrado retorna falha")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com e-mail já cadastrado retorna falha")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComE_MailJaCadastradoRetornaFalha()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com e-mail já cadastrado retorna falha", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync("já existe um usuário cadastrado com o e-mail \"existente@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.WhenAsync("o sistema tenta registrar um usuário com o mesmo e-mail \"existente@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("o resultado de registro deve ser falha com mensagem \"Usuário já cadastrado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com dados válidos retorna sucesso")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com dados válidos retorna sucesso")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComDadosValidosRetornaSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com dados válidos retorna sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
    await testRunner.WhenAsync("o sistema registra um usuário com nome \"João Silva\" e-mail \"joao@fcg.com\" e senha" +
                        " \"Senha@123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("o resultado de registro deve ser sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
    await testRunner.AndAsync("o usuário retornado deve ter nome \"João Silva\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync("o usuário retornado deve ter e-mail \"joao@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com dados válidos publica evento de criação")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com dados válidos publica evento de criação")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComDadosValidosPublicaEventoDeCriacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com dados válidos publica evento de criação", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.WhenAsync("o sistema registra um usuário com nome \"Maria Santos\" e-mail \"maria@fcg.com\" e se" +
                        "nha \"Senha@123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("o evento de criação de usuário deve ter sido publicado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com dados válidos chama repositório para adicionar")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com dados válidos chama repositório para adicionar")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComDadosValidosChamaRepositorioParaAdicionar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com dados válidos chama repositório para adicionar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.WhenAsync("o sistema registra um usuário com nome \"Carlos Souza\" e-mail \"carlos@fcg.com\" e s" +
                        "enha \"Senha@123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("o repositório deve ter sido chamado para adicionar o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Listar todos os usuários retorna a lista completa")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Listar todos os usuários retorna a lista completa")]
        public async global::System.Threading.Tasks.Task ListarTodosOsUsuariosRetornaAListaCompleta()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar todos os usuários retorna a lista completa", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("3 usuários cadastrados no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.WhenAsync("todos os usuários são listados", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
    await testRunner.ThenAsync("devem ser retornados 3 usuários", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Listar usuários com repositório vazio retorna lista vazia")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Listar usuários com repositório vazio retorna lista vazia")]
        public async global::System.Threading.Tasks.Task ListarUsuariosComRepositorioVazioRetornaListaVazia()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar usuários com repositório vazio retorna lista vazia", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("nenhum usuário cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.WhenAsync("todos os usuários são listados", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("devem ser retornados 0 usuários", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Buscar usuário por id existente retorna o usuário")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Buscar usuário por id existente retorna o usuário")]
        public async global::System.Threading.Tasks.Task BuscarUsuarioPorIdExistenteRetornaOUsuario()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar usuário por id existente retorna o usuário", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
    await testRunner.GivenAsync("um usuário cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.WhenAsync("o sistema busca o usuário pelo id cadastrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
    await testRunner.ThenAsync("o usuário deve ser retornado com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Buscar usuário por id inexistente retorna nulo")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Buscar usuário por id inexistente retorna nulo")]
        public async global::System.Threading.Tasks.Task BuscarUsuarioPorIdInexistenteRetornaNulo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar usuário por id inexistente retorna nulo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 51
    await testRunner.WhenAsync("o sistema busca um usuário por id inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("o resultado deve ser nulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Atualizar usuário inexistente retorna nulo")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Atualizar usuário inexistente retorna nulo")]
        public async global::System.Threading.Tasks.Task AtualizarUsuarioInexistenteRetornaNulo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar usuário inexistente retorna nulo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.WhenAsync("o sistema tenta atualizar um usuário com id inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("o resultado deve ser nulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Atualizar usuário existente com novo nome")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Atualizar usuário existente com novo nome")]
        public async global::System.Threading.Tasks.Task AtualizarUsuarioExistenteComNovoNome()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar usuário existente com novo nome", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
    await testRunner.GivenAsync("um usuário cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.WhenAsync("o sistema atualiza o usuário com o nome \"Novo Nome Atualizado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("o usuário deve ter nome \"Novo Nome Atualizado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.AndAsync("o repositório deve ter sido chamado para atualizar o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Desativar usuário existente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Desativar usuário existente")]
        public async global::System.Threading.Tasks.Task DesativarUsuarioExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Desativar usuário existente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
    await testRunner.GivenAsync("um usuário cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
    await testRunner.WhenAsync("o sistema desativa o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
    await testRunner.ThenAsync("o usuário deve estar inativo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GerenciamentoDeUsuariosFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GerenciamentoDeUsuariosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
