// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FCG.UsersAPI.Tests.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeUsuariosFeature : object, global::Xunit.IClassFixture<GerenciamentoDeUsuariosFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "BDD/Features", "Gerenciamento de Usuários", "  Como sistema de gerenciamento de usuários\r\n  Quero registrar e gerenciar usuári" +
                "os\r\n  Para que possam acessar a plataforma FCG Games", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UserService.feature"
#line hidden
        
        public GerenciamentoDeUsuariosFeature(GerenciamentoDeUsuariosFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("BDD/Features/UserService.feature", "Feature: Gerenciamento de Usuários\r\n  Como sistema de gerenciamento de usuários\r\n" +
                    "  Quero registrar e gerenciar usuários\r\n  Para que possam acessar a plataforma F" +
                    "CG Games\r\n\r\n  # ---- RegisterAsync ----\r\n\r\n  Scenario: Registrar usuário com dad" +
                    "os inválidos retorna falha\r\n    When o sistema tenta registrar um usuário com da" +
                    "dos inválidos\r\n    Then o resultado de registro deve ser falha com mensagem \"Inv" +
                    "alid request data\"\r\n\r\n  Scenario: Registrar usuário com e-mail já cadastrado ret" +
                    "orna falha\r\n    Given já existe um usuário cadastrado com o e-mail \"existente@fc" +
                    "g.com\"\r\n    When o sistema tenta registrar um usuário com o mesmo e-mail \"existe" +
                    "nte@fcg.com\"\r\n    Then o resultado de registro deve ser falha com mensagem \"Usuá" +
                    "rio já cadastrado\"\r\n\r\n  Scenario: Registrar usuário com dados válidos retorna su" +
                    "cesso\r\n    When o sistema registra um usuário com nome \"João Silva\" e-mail \"joao" +
                    "@fcg.com\" e senha \"Senha@123\"\r\n    Then o resultado de registro deve ser sucesso" +
                    "\r\n    And o usuário retornado deve ter nome \"João Silva\"\r\n    And o usuário reto" +
                    "rnado deve ter e-mail \"joao@fcg.com\"\r\n\r\n  Scenario: Registrar usuário com dados " +
                    "válidos publica evento de criação\r\n    When o sistema registra um usuário com no" +
                    "me \"Maria Santos\" e-mail \"maria@fcg.com\" e senha \"Senha@123\"\r\n    Then o evento " +
                    "de criação de usuário deve ter sido publicado\r\n\r\n  Scenario: Registrar usuário c" +
                    "om dados válidos chama repositório para adicionar\r\n    When o sistema registra u" +
                    "m usuário com nome \"Carlos Souza\" e-mail \"carlos@fcg.com\" e senha \"Senha@123\"\r\n " +
                    "   Then o repositório deve ter sido chamado para adicionar o usuário\r\n\r\n  # ----" +
                    " GetAll ----\r\n\r\n  Scenario: Listar todos os usuários retorna a lista completa\r\n " +
                    "   Given 3 usuários cadastrados no sistema\r\n    When todos os usuários são lista" +
                    "dos\r\n    Then devem ser retornados 3 usuários\r\n\r\n  Scenario: Listar usuários com" +
                    " repositório vazio retorna lista vazia\r\n    Given nenhum usuário cadastrado no s" +
                    "istema\r\n    When todos os usuários são listados\r\n    Then devem ser retornados 0" +
                    " usuários\r\n\r\n  # ---- GetById ----\r\n\r\n  Scenario: Buscar usuário por id existent" +
                    "e retorna o usuário\r\n    Given um usuário cadastrado no sistema\r\n    When o sist" +
                    "ema busca o usuário pelo id cadastrado\r\n    Then o usuário deve ser retornado co" +
                    "m sucesso\r\n\r\n  Scenario: Buscar usuário por id inexistente retorna nulo\r\n    Whe" +
                    "n o sistema busca um usuário por id inexistente\r\n    Then o resultado deve ser n" +
                    "ulo\r\n\r\n  # ---- Update ----\r\n\r\n  Scenario: Atualizar usuário inexistente retorna" +
                    " nulo\r\n    When o sistema tenta atualizar um usuário com id inexistente\r\n    The" +
                    "n o resultado deve ser nulo\r\n\r\n  Scenario: Atualizar usuário existente com novo " +
                    "nome\r\n    Given um usuário cadastrado no sistema\r\n    When o sistema atualiza o " +
                    "usuário com o nome \"Novo Nome Atualizado\"\r\n    Then o usuário deve ter nome \"Nov" +
                    "o Nome Atualizado\"\r\n    And o repositório deve ter sido chamado para atualizar o" +
                    " usuário\r\n\r\n  Scenario: Desativar usuário existente\r\n    Given um usuário cadast" +
                    "rado no sistema\r\n    When o sistema desativa o usuário\r\n    Then o usuário deve " +
                    "estar inativo\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("BDD/Features/UserService.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Gerenciamento de Usuários", "  Como sistema de gerenciamento de usuários\r\n  Quero registrar e gerenciar usuári" +
                        "os\r\n  Para que possam acessar a plataforma FCG Games", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com dados inválidos retorna falha", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema tenta registrar um usuário com dados inválidos", null, null, "95b7a1f47190e05e8bcf6c92f660a091"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado de registro deve ser falha com mensagem \"Invalid request data\"", null, null, "e726964e71f4d450908af5279de32113")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "07e1c2e0a3a4c45faa1e35e74d542fb7")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com e-mail já cadastrado retorna falha", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "já existe um usuário cadastrado com o e-mail \"existente@fcg.com\"", null, null, "2dee0c8a53d68b5dbcb107e12512b7c8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema tenta registrar um usuário com o mesmo e-mail \"existente@fcg.com\"", null, null, "f5b871efddf84c5786cf88cd16462a00"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado de registro deve ser falha com mensagem \"Usuário já cadastrado\"", null, null, "2adc289136b6425e96aa0c2b532e2f62")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b0c74fc9f453585a88f042895d317d97")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com dados válidos retorna sucesso", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema registra um usuário com nome \"João Silva\" e-mail \"joao@fcg.com\" e senha" +
                                                            " \"Senha@123\"", null, null, "3d257cb1b099fe5bb8cf92f271bfcc46"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado de registro deve ser sucesso", null, null, "32b0df6af4d7385295a0357374e8f1f5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o usuário retornado deve ter nome \"João Silva\"", null, null, "8ddcea4526ba015db6a983d4bad22008"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o usuário retornado deve ter e-mail \"joao@fcg.com\"", null, null, "7911583f7fe10553ad57738a7f9cd565")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "4c17b8944e1434559e86418ca21a35a4")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com dados válidos publica evento de criação", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema registra um usuário com nome \"Maria Santos\" e-mail \"maria@fcg.com\" e se" +
                                                            "nha \"Senha@123\"", null, null, "2c7f08321f826d5d8b82c23742065658"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o evento de criação de usuário deve ter sido publicado", null, null, "7d73a0013c610f5fac93325bbd4d4699")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0e2f933fcd96f0529fd3627ef5d43a1c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Registrar usuário com dados válidos chama repositório para adicionar", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema registra um usuário com nome \"Carlos Souza\" e-mail \"carlos@fcg.com\" e s" +
                                                            "enha \"Senha@123\"", null, null, "e9b97f407b99285a8b453ea1ee3f5bb6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o repositório deve ter sido chamado para adicionar o usuário", null, null, "f2ae597a8d8b0558b464741dd3e300b5")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "6eac859b15fccd59bd32d3db919dd9eb")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Listar todos os usuários retorna a lista completa", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "3 usuários cadastrados no sistema", null, null, "d4d36f32ef38715788026053a5c4def6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "todos os usuários são listados", null, null, "a6dcf727037e3154a0600cd75e278b7b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devem ser retornados 3 usuários", null, null, "71d64fd687f88a50b05234a88e6d1a7c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e579ff8cfcdf035faefeb2fb8ddea899")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Listar usuários com repositório vazio retorna lista vazia", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "nenhum usuário cadastrado no sistema", null, null, "4127e2cc4b0ac95c97a623fe2690bfe1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "todos os usuários são listados", null, null, "5247b945ae3d375e8df967f141853be8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devem ser retornados 0 usuários", null, null, "24a8b84374c60c57b365b29dce08068f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0fd54b12f1b53a5fbb9653eab15803a6")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Buscar usuário por id existente retorna o usuário", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um usuário cadastrado no sistema", null, null, "380b94e9677d6259a241972ff965ba69"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema busca o usuário pelo id cadastrado", null, null, "7b4d4950c7357e599dbcdc76bed71c6f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o usuário deve ser retornado com sucesso", null, null, "22eac5e9761f5e5c9aa3e1abd50904f8")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "ee535d2392520850add8a926d1fd445e")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Buscar usuário por id inexistente retorna nulo", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema busca um usuário por id inexistente", null, null, "1b2d5c5ad4f5a05192bfedd44d703f79"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado deve ser nulo", null, null, "3ccfcbea6905d8529fdc02dd72de488c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "132298aeaddcda5a86942a45b63e2366")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Atualizar usuário inexistente retorna nulo", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema tenta atualizar um usuário com id inexistente", null, null, "348f5ce65b321f518806ace5590699ab"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(58, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o resultado deve ser nulo", null, null, "69151170e7618358acdfa10baec7c833")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "6181f27d9fc8b352bad7dd9b34256ba0")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Atualizar usuário existente com novo nome", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um usuário cadastrado no sistema", null, null, "6f6d3def7b016457890d6183f8bab99f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema atualiza o usuário com o nome \"Novo Nome Atualizado\"", null, null, "685541b3ddf367599ca27e0d78cd7c4a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(63, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o usuário deve ter nome \"Novo Nome Atualizado\"", null, null, "54367c0373cbbe51825c7c9e219d43d5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(64, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o repositório deve ter sido chamado para atualizar o usuário", null, null, "875b184b4013dd5db81aea4490816319")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3964a601aad67e599a180678400fd47a")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(66, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Desativar usuário existente", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(67, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um usuário cadastrado no sistema", null, null, "133da37c4957e450b2f5ee38b3b6ad69"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(68, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o sistema desativa o usuário", null, null, "0020199c6bbfbe5ea230849c3f6445b4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(69, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o usuário deve estar inativo", null, null, "a25213a8bb5fb85f9f5ab820933df286")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "6f909babd44aa157a5481625e92157be"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[] {
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), "  # ---- RegisterAsync ----"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(1)), "  # ---- GetAll ----"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(43, new System.Nullable<long>(1)), "  # ---- GetById ----"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(1)), "  # ---- Update ----")}));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("37d3774b4c2be05b9d408b5ff7e9559c", "BDD/Features/UserService.feature", "Registrar usuário com dados inválidos retorna falha", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "95b7a1f47190e05e8bcf6c92f660a091"}), "927adfd4be3d6758bcc914ab003ee05d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema tenta registrar um usuário com dados inválidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e726964e71f4d450908af5279de32113"}), "c2a95d15c61c7959a91c3fd0b5288f44", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado de registro deve ser falha com mensagem \"Invalid request data\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "07e1c2e0a3a4c45faa1e35e74d542fb7"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("4846f19a94cbf65fa0662c1a96c57aa8", "BDD/Features/UserService.feature", "Registrar usuário com e-mail já cadastrado retorna falha", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2dee0c8a53d68b5dbcb107e12512b7c8"}), "54074a50121e22578a44f2636b476a72", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "já existe um usuário cadastrado com o e-mail \"existente@fcg.com\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f5b871efddf84c5786cf88cd16462a00"}), "e6622dd7eaa9a95b8605d57d3008df19", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema tenta registrar um usuário com o mesmo e-mail \"existente@fcg.com\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2adc289136b6425e96aa0c2b532e2f62"}), "ccc73dcac755785ebfb7a138d9f6450e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado de registro deve ser falha com mensagem \"Usuário já cadastrado\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "b0c74fc9f453585a88f042895d317d97"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("27ce91380e50275bb97cf2ffbd34a6e8", "BDD/Features/UserService.feature", "Registrar usuário com dados válidos retorna sucesso", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3d257cb1b099fe5bb8cf92f271bfcc46"}), "de66c935bc3b6558bab68099bab59c09", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema registra um usuário com nome \"João Silva\" e-mail \"joao@fcg.com\" e senha" +
                                                " \"Senha@123\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "32b0df6af4d7385295a0357374e8f1f5"}), "d7e6171f7430125493d26495d3d62f2f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado de registro deve ser sucesso"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8ddcea4526ba015db6a983d4bad22008"}), "b6f254545c1fb7578fb44f27adb62a6d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário retornado deve ter nome \"João Silva\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7911583f7fe10553ad57738a7f9cd565"}), "374219a91c0607589d8ad0134744f971", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário retornado deve ter e-mail \"joao@fcg.com\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "4c17b8944e1434559e86418ca21a35a4"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("0639f8b8bc987b5a9267425f5a5d85b4", "BDD/Features/UserService.feature", "Registrar usuário com dados válidos publica evento de criação", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2c7f08321f826d5d8b82c23742065658"}), "e3115f7e505f345cbdaaeab7d8501e4c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema registra um usuário com nome \"Maria Santos\" e-mail \"maria@fcg.com\" e se" +
                                                "nha \"Senha@123\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7d73a0013c610f5fac93325bbd4d4699"}), "042e1367cabf485ab1b51d3902a8b875", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o evento de criação de usuário deve ter sido publicado")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "0e2f933fcd96f0529fd3627ef5d43a1c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("8cd678741bb70158928fc4941a13f34f", "BDD/Features/UserService.feature", "Registrar usuário com dados válidos chama repositório para adicionar", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e9b97f407b99285a8b453ea1ee3f5bb6"}), "83be91a9647fcc5ebcb5755e4fa6976e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema registra um usuário com nome \"Carlos Souza\" e-mail \"carlos@fcg.com\" e s" +
                                                "enha \"Senha@123\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f2ae597a8d8b0558b464741dd3e300b5"}), "f5105107b16af85bbaccf1a13c4dba41", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o repositório deve ter sido chamado para adicionar o usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "6eac859b15fccd59bd32d3db919dd9eb"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6c18ac58f6ee5858ae9d30f04e34f017", "BDD/Features/UserService.feature", "Listar todos os usuários retorna a lista completa", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d4d36f32ef38715788026053a5c4def6"}), "05c324075416795fabc16cdba117eec9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "3 usuários cadastrados no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a6dcf727037e3154a0600cd75e278b7b"}), "66ab1e5d8423da58a1d07cce7dad01ef", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "todos os usuários são listados"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "71d64fd687f88a50b05234a88e6d1a7c"}), "06f769aa33b1ac5da317e62c742fcb54", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devem ser retornados 3 usuários")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "e579ff8cfcdf035faefeb2fb8ddea899"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("94ea323a3bdbc45f9fa9d17e2b7ac049", "BDD/Features/UserService.feature", "Listar usuários com repositório vazio retorna lista vazia", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4127e2cc4b0ac95c97a623fe2690bfe1"}), "add6eebb6635e157b52194d308f1e9a2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "nenhum usuário cadastrado no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5247b945ae3d375e8df967f141853be8"}), "386ce29869956b57820f712d887d5682", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "todos os usuários são listados"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "24a8b84374c60c57b365b29dce08068f"}), "4307345d84d7785caeb40bd422a8698f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devem ser retornados 0 usuários")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "0fd54b12f1b53a5fbb9653eab15803a6"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("1ae988f4acae535481185c235b766f92", "BDD/Features/UserService.feature", "Buscar usuário por id existente retorna o usuário", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "380b94e9677d6259a241972ff965ba69"}), "30d333780babe951ba0af1eefbe5cd32", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um usuário cadastrado no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7b4d4950c7357e599dbcdc76bed71c6f"}), "850346e7b970f659b58a97daa1ed7156", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema busca o usuário pelo id cadastrado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "22eac5e9761f5e5c9aa3e1abd50904f8"}), "ddef952f2a47df5b91fa9fc36ea5009c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário deve ser retornado com sucesso")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "ee535d2392520850add8a926d1fd445e"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3b8036e4716a9755b90522fcacdc733c", "BDD/Features/UserService.feature", "Buscar usuário por id inexistente retorna nulo", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1b2d5c5ad4f5a05192bfedd44d703f79"}), "4f9498d059d60d53acc88d0fb5041667", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema busca um usuário por id inexistente"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3ccfcbea6905d8529fdc02dd72de488c"}), "54d478f24cb99755b2c4cbd23bb46c1c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado deve ser nulo")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "132298aeaddcda5a86942a45b63e2366"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("93200991cbb2c252bc3140f5f583f56c", "BDD/Features/UserService.feature", "Atualizar usuário inexistente retorna nulo", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "348f5ce65b321f518806ace5590699ab"}), "2524436e39497850b5e1679d39b09259", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema tenta atualizar um usuário com id inexistente"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "69151170e7618358acdfa10baec7c833"}), "b3add3258d3a1e51be665477a718af13", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o resultado deve ser nulo")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "6181f27d9fc8b352bad7dd9b34256ba0"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("e66bd0a48bc7725ea24fd0a2197b57af", "BDD/Features/UserService.feature", "Atualizar usuário existente com novo nome", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6f6d3def7b016457890d6183f8bab99f"}), "7cfb4b890bb1da5294669d2ff4af4497", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um usuário cadastrado no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "685541b3ddf367599ca27e0d78cd7c4a"}), "b190ea028649395ca7cd73f8776ff098", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema atualiza o usuário com o nome \"Novo Nome Atualizado\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "54367c0373cbbe51825c7c9e219d43d5"}), "e8212c362157b151bb2345f6f7e47dcb", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário deve ter nome \"Novo Nome Atualizado\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "875b184b4013dd5db81aea4490816319"}), "042b7f03df16685f8f891c07fc134120", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o repositório deve ter sido chamado para atualizar o usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "3964a601aad67e599a180678400fd47a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("0ca25d9dd6729b578a85d444d75516e2", "BDD/Features/UserService.feature", "Desativar usuário existente", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "133da37c4957e450b2f5ee38b3b6ad69"}), "0522c4e36428ce5084196600624b0f42", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um usuário cadastrado no sistema"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0020199c6bbfbe5ea230849c3f6445b4"}), "a1a55498fd7c045cb52a1941d0b641a9", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o sistema desativa o usuário"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a25213a8bb5fb85f9f5ab820933df286"}), "237018cec418925aa5e8799092d0fab2", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o usuário deve estar inativo")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "6f909babd44aa157a5481625e92157be"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(GerenciamentoDeUsuariosFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(GerenciamentoDeUsuariosFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(GerenciamentoDeUsuariosFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com dados inválidos retorna falha")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com dados inválidos retorna falha")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComDadosInvalidosRetornaFalha()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com dados inválidos retorna falha", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.WhenAsync("o sistema tenta registrar um usuário com dados inválidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync("o resultado de registro deve ser falha com mensagem \"Invalid request data\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com e-mail já cadastrado retorna falha")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com e-mail já cadastrado retorna falha")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComE_MailJaCadastradoRetornaFalha()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com e-mail já cadastrado retorna falha", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync("já existe um usuário cadastrado com o e-mail \"existente@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.WhenAsync("o sistema tenta registrar um usuário com o mesmo e-mail \"existente@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("o resultado de registro deve ser falha com mensagem \"Usuário já cadastrado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com dados válidos retorna sucesso")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com dados válidos retorna sucesso")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComDadosValidosRetornaSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com dados válidos retorna sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
    await testRunner.WhenAsync("o sistema registra um usuário com nome \"João Silva\" e-mail \"joao@fcg.com\" e senha" +
                        " \"Senha@123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("o resultado de registro deve ser sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
    await testRunner.AndAsync("o usuário retornado deve ter nome \"João Silva\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync("o usuário retornado deve ter e-mail \"joao@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com dados válidos publica evento de criação")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com dados válidos publica evento de criação")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComDadosValidosPublicaEventoDeCriacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com dados válidos publica evento de criação", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.WhenAsync("o sistema registra um usuário com nome \"Maria Santos\" e-mail \"maria@fcg.com\" e se" +
                        "nha \"Senha@123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("o evento de criação de usuário deve ter sido publicado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar usuário com dados válidos chama repositório para adicionar")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Registrar usuário com dados válidos chama repositório para adicionar")]
        public async global::System.Threading.Tasks.Task RegistrarUsuarioComDadosValidosChamaRepositorioParaAdicionar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar usuário com dados válidos chama repositório para adicionar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.WhenAsync("o sistema registra um usuário com nome \"Carlos Souza\" e-mail \"carlos@fcg.com\" e s" +
                        "enha \"Senha@123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("o repositório deve ter sido chamado para adicionar o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Listar todos os usuários retorna a lista completa")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Listar todos os usuários retorna a lista completa")]
        public async global::System.Threading.Tasks.Task ListarTodosOsUsuariosRetornaAListaCompleta()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar todos os usuários retorna a lista completa", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("3 usuários cadastrados no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.WhenAsync("todos os usuários são listados", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
    await testRunner.ThenAsync("devem ser retornados 3 usuários", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Listar usuários com repositório vazio retorna lista vazia")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Listar usuários com repositório vazio retorna lista vazia")]
        public async global::System.Threading.Tasks.Task ListarUsuariosComRepositorioVazioRetornaListaVazia()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar usuários com repositório vazio retorna lista vazia", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("nenhum usuário cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.WhenAsync("todos os usuários são listados", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("devem ser retornados 0 usuários", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Buscar usuário por id existente retorna o usuário")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Buscar usuário por id existente retorna o usuário")]
        public async global::System.Threading.Tasks.Task BuscarUsuarioPorIdExistenteRetornaOUsuario()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar usuário por id existente retorna o usuário", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
    await testRunner.GivenAsync("um usuário cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.WhenAsync("o sistema busca o usuário pelo id cadastrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
    await testRunner.ThenAsync("o usuário deve ser retornado com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Buscar usuário por id inexistente retorna nulo")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Buscar usuário por id inexistente retorna nulo")]
        public async global::System.Threading.Tasks.Task BuscarUsuarioPorIdInexistenteRetornaNulo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar usuário por id inexistente retorna nulo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 51
    await testRunner.WhenAsync("o sistema busca um usuário por id inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("o resultado deve ser nulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Atualizar usuário inexistente retorna nulo")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Atualizar usuário inexistente retorna nulo")]
        public async global::System.Threading.Tasks.Task AtualizarUsuarioInexistenteRetornaNulo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar usuário inexistente retorna nulo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.WhenAsync("o sistema tenta atualizar um usuário com id inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("o resultado deve ser nulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Atualizar usuário existente com novo nome")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Atualizar usuário existente com novo nome")]
        public async global::System.Threading.Tasks.Task AtualizarUsuarioExistenteComNovoNome()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar usuário existente com novo nome", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
    await testRunner.GivenAsync("um usuário cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.WhenAsync("o sistema atualiza o usuário com o nome \"Novo Nome Atualizado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("o usuário deve ter nome \"Novo Nome Atualizado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.AndAsync("o repositório deve ter sido chamado para atualizar o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Desativar usuário existente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Desativar usuário existente")]
        public async global::System.Threading.Tasks.Task DesativarUsuarioExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Desativar usuário existente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
    await testRunner.GivenAsync("um usuário cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
    await testRunner.WhenAsync("o sistema desativa o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
    await testRunner.ThenAsync("o usuário deve estar inativo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GerenciamentoDeUsuariosFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GerenciamentoDeUsuariosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
